Repository koolgreg2009/group8csc207, pull requests merged in 2024-07, with the labels that each got.

#4 i added more entities
  .idea/uiDesigner.xml
  src/entity/AdopterInterface.java
  src/entity/AdopterUser.java
  src/entity/AdopterUserFactory.java
  src/entity/User.java
  src/entity/UserFactory.java
  src/utils/IdCounter.java
Labels: help wanted

#8 hello
  src/entity/Pet.java
Labels: enhancement, help wanted

#16 made changes
  src/entity/User/AdopterUser.java
Labels: help wanted

#17 help
  src/entity/User/AdopterInterface.java
Labels: help wanted

#22 added output boundary
  src/use_case/BookmarkInputBoundary.java
Labels: bug

#29 use case for Justin initalized
  src/use_case/signup/SignupInputBoundary.java
  src/use_case/signup/SignupInputData.java
  src/use_case/signup/SignupInputInteractor.java
  src/use_case/signup/SignupOutputBoundary.java
  src/use_case/signup/SignupOutputData.java
  src/use_case/signup/SignupUserDataAccessInterface.java
Labels: good first issue

#40 made fixes to signupusecase
  src/app/SignupUseCaseFactory.java
  src/data_access/FileUserDAO.java
  src/interface_adapter/SignupController.java
  src/use_case/SignupInputData.java
  src/use_case/SignupInteractor.java
Labels: enhancement

#48 initial implementation of bookmarkusecase
  src/use_case/bookmarkUsecase/AddBookmarkUsecaseInteractor.java
  src/use_case/bookmarkUsecase/BookmarkInputBoundary.java
  src/use_case/bookmarkUsecase/BookmarkInputData.java
  src/use_case/bookmarkUsecase/BookmarkOutputboundary.java
  src/use_case/bookmarkUsecase/BookmarkOutputdata.java
Labels: help wanted

#49 added userhasboomark in userdao
  src/data_access/FileUserDAO.java
Labels: help wanted

#50 moved prefrenceusecase files around
  src/use_case/PreferenceInputBoundary.java
  src/use_case/PreferenceUseCase/PreferenceData.java
  src/use_case/PreferenceUseCase/PreferenceInputBoundary.java
  src/use_case/PreferenceUseCase/PreferenceOutputBoundary.java
  src/use_case/PreferenceUseCase/PreferenceOutputData.java
Labels: enhancement

#53 added getters for some fields in pet
  src/entity/Pet.java
Labels: enhancement

#52 i fixed something i forgot what but it took an extra argument
  src/entity/Preference/UserPreference.java
Labels: bug

#55 login state implemented
  src/app/LoginUseCaseFactory.java
  src/app/Main.java
  src/app/SignupUseCaseFactory.java
  src/interface_adapter/logged_in/LoggedInState.java
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/interface_adapter/login/LoginController.java
  src/interface_adapter/login/LoginPresenter.java
  src/interface_adapter/login/LoginState.java
  src/interface_adapter/login/LoginViewModel.java
  src/interface_adapter/signup/SignupController.java
  src/interface_adapter/signup/SignupPresenter.java
  src/interface_adapter/signup/SignupState.java
  src/interface_adapter/signup/SignupViewModel.java
  src/use_case/login/LoginInputBoundary.java
  src/use_case/login/LoginInputData.java
  src/use_case/login/LoginInteractor.java
  src/use_case/login/LoginOutputBoundary.java
  src/use_case/login/LoginOutputData.java
  src/use_case/login/LoginUserDataAccessInterface.java
  src/use_case/signup/SignupInputBoundary.java
  src/use_case/signup/SignupInputData.java
  src/use_case/signup/SignupInteractor.java
  src/use_case/signup/SignupOutputBoundary.java
  src/use_case/signup/SignupOutputData.java
  src/view/LoggedInView.java
  src/view/LoginView.java
  src/view/SignupView.java
  src/view/ViewManager.java
Labels: documentation

#59 fixed pet dao interface, added team use case implementation, and some other small fixes
  src/data_access/FileUserDAO.java
  src/data_access/UserDAOInterface.java
  src/use_case/bookmarkUsecase/AddBookmarkUsecaseInteractor.java
  src/use_case/bookmarkUsecase/BookmarkInputData.java
  src/use_case/displayAllAvailablePets/displayAllPetsInputBoundary.java
  src/use_case/displayAllAvailablePets/displayAllPetsInteractor.java
  src/use_case/displayAllAvailablePets/displayAllPetsOutputBoundary.java
  src/use_case/displayAllAvailablePets/displayInputData.java
  target/classes/data_access/FilePetDAO.class
  target/classes/entity/Preference/UserPreference.class
Labels: bug

#60 quick fix
  src/data_access/FilePetDAO.java
  src/data_access/PetDAOInterface.java
Labels: bug

#80 PetBio Use Case, Console Template
  src/app/Main.java
  src/entity/Pet.java
  src/interface_adapter/pet_bio/PetBioPresenter.java
  src/use_case/pet_bio/PetBioInputBoundary.java
  src/use_case/pet_bio/PetBioInputData.java
  src/use_case/pet_bio/PetBioInteractor.java
  src/use_case/pet_bio/PetBioOutputBoundary.java
  src/use_case/pet_bio/PetBioOutputData.java
Labels: enhancement

#92 added presenters
  src/interface_adapter/bookmark/AddBookmarkPresenter.java
  src/interface_adapter/display_all_pets/DisplayAllPetsPresenter.java
  src/interface_adapter/get_breed/GetBreedPresenter.java
  src/use_case/bookmarks/AddBookmarkInteractor.java
  src/use_case/bookmarks/AddBookmarkOutputBoundary.java
  src/use_case/bookmarks/AddBookmarkOutputData.java
  src/use_case/bookmarks/BookmarkOutputBoundary.java
  src/use_case/bookmarks/BookmarkOutputData.java
  src/use_case/bookmarks/BookmarkPresenter.java
  src/use_case/display_all_available_pets/DisplayAllPetsInputBoundary.java
  src/use_case/display_all_available_pets/DisplayAllPetsInputData.java
  src/use_case/display_all_available_pets/DisplayAllPetsInteractor.java
  src/use_case/display_all_available_pets/DisplayAllPetsOutputBoundary.java
  src/use_case/display_all_available_pets/DisplayAllPetsOutputData.java
  src/use_case/display_all_available_pets/displayAllPetsInputBoundary.java
  src/use_case/display_all_available_pets/displayAllPetsInteractor.java
  src/use_case/display_all_available_pets/displayAllPetsOutputBoundary.java
  src/use_case/get_breed_info/GetBreedInputBoundary.java
  src/use_case/get_breed_info/GetBreedInputData.java
  src/use_case/get_breed_info/GetBreedInteractor.java
  src/use_case/get_breed_info/GetBreedOutputBoundary.java
  src/use_case/get_breed_info/GetBreedOutputData.java
  src/use_case/get_breed_info/getBreedInputBoundary.java
  src/use_case/get_breed_info/getBreedOutputBoundary.java
Labels: new feature

#96 i worked on addbookmarkusecase and made some changes or something if orgot
  src/app/AddBookmarkUsecaseFactory.java
  src/app/GetBreedUsecaseFactory.java
  src/entity/user/AdopterUser.java
  src/entity/user/CommonUser.java
  src/entity/user/User.java
  src/interface_adapter/bookmark/AddBookmarkController.java
  src/use_case/bookmarks/AddBookmarkInteractor.java
Labels: new feature

#103 i finished some use cases
  src/app/AddBookmarkUsecaseFactory.java
  src/app/DisplayAllPetsUsecaseFactory.java
  src/interface_adapter/display_all_pets/DisplayAllPetsController.java
  src/use_case/display_all_available_pets/DisplayAllPetsInteractor.java
Labels: new feature

#106 Pet JSON testing
  pets.json
  src/app/Main.java
  src/app/PetBioUseCaseFactory.java
  src/data_access/FilePetDAO.java
  src/entity/Pet.java
  src/interface_adapter/pet_bio/PetBioPresenter.java
Labels: new feature

#109 deleted more scanner.close
  src/interface_adapter/adopt/AdoptController.java
  src/interface_adapter/bookmark/AddBookmarkController.java
  src/interface_adapter/get_breed/GetBreedController.java
Labels: bug

#112 bookmark time thing
  pets.json
  src/app/Main.java
  src/data_access/FilePetDAO.java
  src/data_access/FileUserDAO.java
  users.json
Labels: bug

#114 DisplayAllPets and Signup Main implementations
  pets.json
  src/app/Main.java
  src/app/SignupUseCaseFactory.java
  src/data_access/FilePetDAO.java
  src/entity/Pet.java
  src/entity/PetFactory.java
  src/entity/user/AdopterUserFactory.java
  src/view/SignupView.java
Labels: new feature

#123 capitalization fix
  src/app/Main.java
Labels: bug

#125 preference fix
  src/interface_adapter/preference/PreferenceController.java
Labels: bug

#127 i am trying to add a way to track logged in user
  src/interface_adapter/SessionManager.java
  src/interface_adapter/login/LoginPresenter.java
Labels: new feature

#129 i added current user logic
  src/data_access/FilePetDAO.java
  src/interface_adapter/bookmark/AddBookmarkController.java
  src/interface_adapter/bookmark/RemoveBookmarkController.java
Labels: bug

#135 pet unavailable
  src/use_case/adopt/Adopt.java
Labels: bug

#173 testing ui part 2
  src/PetAdoptionUI.java
Labels: question

#174 login view
  src/app/LoginUseCaseFactory.java
  src/app/Main.java
  src/app/SignupUseCaseFactory.java
  src/interface_adapter/login/LoginController.java
  src/interface_adapter/login/LoginPresenter.java
  src/interface_adapter/login/LoginState.java
  src/interface_adapter/login/LoginViewModel.java
  src/interface_adapter/signup/SignupViewModel.java
  src/use_case/login/LoginInteractor.java
  src/use_case/login/LoginOutputData.java
  src/view/LoginView.java
  src/view/SignupView.java
Labels: new feature

#176 fixed dao bug
  src/app/Main.java
Labels: bug

#181 added partial display bookmark pets use case
  src/app/DisplayAllPetsUseCaseFactory.java
  src/app/DisplayBookmarkUseCaseFactory.java
  src/interface_adapter/display_all_pets/DisplayAllPetsController.java
  src/interface_adapter/display_all_pets/DisplayAllPetsPresenter.java
  src/interface_adapter/display_all_pets/DisplayPetsPresenter.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkController.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkPresenter.java
  src/use_case/display/DisplayPetsOutputBoundary.java
  src/use_case/display/DisplayPetsOutputData.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInputBoundary.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInputData.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInteractor.java
  src/use_case/display/display_bookmark_pets/DisplayBookmarkInputBoundary.java
  src/use_case/display/display_bookmark_pets/DisplayBookmarkInputData.java
  src/use_case/display/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_all_available_pets/DisplayAllPetsOutputBoundary.java
Labels: new feature

#182 added json parsing for cat api dao
  pom.xml
  src/data_access/CatBreedDAO.java
  src/data_access/CatDAOInterface.java
  src/interface_adapter/get_breed/GetBreedController.java
  src/interface_adapter/get_breed/GetBreedPresenter.java
  src/use_case/get_breed_info/GetBreedInteractor.java
  src/use_case/get_breed_info/GetBreedOutputData.java
  test/use_case/get_breed_info/GetBreedInteractorTest.java
Labels: new feature

#185 refactored displayallpets to displaypets for output boundary and data
  src/interface_adapter/display_all_pets/DisplayPetsPresenter.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkPresenter.java
  src/use_case/display/DisplayPetsOutputBoundary.java
  src/use_case/display/DisplayPetsOutputData.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInteractor.java
  src/use_case/display/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_all_available_pets/DisplayAllPetsOutputBoundary.java
Labels: bug fix
