Repository koolgreg2009/group8csc207, pull requests merged in 2024-08, with the labels that each got.

#187 almost completed new api dao
  pets.json
  src/data_access/FilePetDAO.java
  src/entity/Pet.java
  src/utils/IdCounter.java
Labels: new feature

#189 pet grab dao implementation and added error handling logic for get breed dao
  src/data_access/FilePetDAO.java
  src/interface_adapter/get_breed/GetBreedPresenter.java
  src/use_case/get_breed_info/GetBreedInteractor.java
  src/use_case/get_breed_info/GetBreedOutputBoundary.java
Labels: new feature, bug fix

#190 new fix
  src/data_access/CatBreedDAO.java
  src/data_access/FilePetDAO.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInputBoundary.java
Labels: bug fix

#191 Uncommented Singup stuff & a bit of editing
  src/app/SignupUseCaseFactory.java
  src/interface_adapter/signup/SignupController.java
  src/interface_adapter/signup/SignupPresenter.java
  src/view/SignupView.java
Labels: bug fix

#205 formatting and fixes
  src/app/Main.java
  src/data_access/FilePetDAO.java
  src/data_access/PetDAOInterface.java
  src/entity/Pet.java
  src/use_case/signup/SignupInteractor.java
  src/view/LoggedInView.java
  src/view/PreferenceView.java
  src/view/SignupView.java
Labels: bug fix

#206 Sign up bug fixed
  src/use_case/signup/SignupInteractor.java
  src/view/SignupView.java
Labels: bug fix

#208 initial formatting of pet listings
  src/app/Main.java
  src/view/LoggedInView.java
Labels: new feature

#213 home page, login/signup bug, pet bio
  src/app/LoggedInUseCaseFactory.java
  src/app/LoginUseCaseFactory.java
  src/app/Main.java
  src/app/SignupUseCaseFactory.java
  src/data_access/FilePetDAO.java
  src/data_access/PetDAOInterface.java
  src/dto/pet/PetDTO.java
  src/interface_adapter/logged_in/LoggedInState.java
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/interface_adapter/login/LoginPresenter.java
  src/interface_adapter/pet_bio/PetBioController.java
  src/interface_adapter/pet_bio/PetBioPresenter.java
  src/interface_adapter/pet_bio/PetBioState.java
  src/interface_adapter/pet_bio/PetBioVIewModel.java
  src/interface_adapter/signup/SignupState.java
  src/use_case/login/LoginInteractor.java
  src/use_case/login/LoginOutputData.java
  src/use_case/pet_bio/PetBioInteractor.java
  src/use_case/pet_bio/PetBioOutputData.java
  src/view/LoggedInView.java
  src/view/PetActionView.java
  src/view/PetListingPanel.java
  src/view/SignupView.java
  target/classes/use_case/login/LoginOutputData.class
Labels: new feature, bug fix

#217 display current user in loggedinview
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/view/LoggedInView.java
  users.json
Labels: new feature

#219 Sign up Update
  src/app/SignupUseCaseFactory.java
  src/view/SignupView.java
Labels: new feature

#221 displaypets now runs everytime page is loggedview
  src/app/DisplayAllPetsUseCaseFactory.java
  src/app/LoggedInUseCaseFactory.java
  src/app/Main.java
  src/data_access/FilePetDAO.java
  src/interface_adapter/display_all_pets/DisplayPetsPresenter.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkPresenter.java
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/interface_adapter/login/LoginPresenter.java
  src/use_case/display/DisplayPetsOutputData.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInteractor.java
  src/use_case/display/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_all_available_pets/DisplayAllPetsOutputBoundary.java
  src/use_case/login/LoginInteractor.java
  src/use_case/login/LoginOutputData.java
  src/view/LoggedInView.java
Labels: new feature

#222 added button logic to adopt
  src/app/AddBookmarkUseCaseFactory.java
  src/app/AdoptUseCaseFactory.java
  src/app/LoggedInUseCaseFactory.java
  src/app/RemoveBookmarkUseCaseFactory.java
  src/interface_adapter/adopt/AdoptController.java
  src/view/LoggedInView.java
Labels: new feature

#226 i added addbookmark button and started doing pop up fo rit
  src/app/AddBookmarkUseCaseFactory.java
  src/app/LoggedInUseCaseFactory.java
  src/interface_adapter/bookmark/AddBookmarkController.java
  src/interface_adapter/bookmark/AddBookmarkPresenter.java
  src/interface_adapter/bookmark/RemoveBookmarkController.java
  src/interface_adapter/logged_in/LoggedInState.java
  src/view/LoggedInView.java
  src/view/PetActionView.java
  src/view/PetListingPanel.java
  test/use_case/bookmarks/AddBookmarkInteractorTest.java
Labels: new feature

#229 added addbookmark validation
  src/interface_adapter/bookmark/AddBookmarkPresenter.java
  src/interface_adapter/logged_in/LoggedInState.java
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/view/LoggedInView.java
  test/use_case/display_all_available_pets/DisplayAllPetsInteractorTest.java
Labels: new feature

#241 fixed red code
  src/app/Main.java
  src/app/PetDetailUseCaseFactory.java
  src/use_case/display/display_all_available_pets/DisplayAllPetsInteractor.java
  src/use_case/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_pets/DisplayPetsInteractor.java
  src/use_case/display_pets/DisplayPetsOutputData.java
  src/view/PetDetailView.java
  src/view/PetListing.java
  src/view/PreferenceView.java
Labels: bug fix

#244 integrated adopt with ui and fixed petdao
  src/app/AdoptUseCaseFactory.java
  src/app/LoggedInUseCaseFactory.java
  src/app/Main.java
  src/data_access/FilePetDAO.java
  src/entity/Pet.java
  src/interface_adapter/adopt/AdoptPresenter.java
  src/interface_adapter/logged_in/LoggedInViewModel.java
  src/use_case/adopt/Adopt.java
  src/use_case/adopt/AdoptOutputData.java
  src/view/LoggedInView.java
  test/use_case/adopt/AdoptTest.java
Labels: new feature

#245 madecorrections to displaybookmark pet
  src/app/DisplayBookmarkUseCaseFactory.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkBookmarkPresenter.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkController.java
  src/use_case/display_bookmark_pets/DisplayBookmarkInputData.java
  src/use_case/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_bookmark_pets/DisplayBookmarkPetsOutputData.java
  test/use_case/display_all_available_pets/DisplayAllPetsInteractorTest.java
Labels: help wanted

#250 display all pets fix part 5
  src/data_access/FilePetDAO.java
  src/use_case/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/use_case/display_pets/DisplayPetsInteractor.java
  src/use_case/login/LoginUserDataAccessInterface.java
Labels: bug fix

#265 part 4
  src/app/Main.java
Labels: bug fix

#264 changed flow from sign up -> pref
  src/app/SignupUseCaseFactory.java
  src/interface_adapter/signup/SignupPresenter.java
  src/view/SignupView.java
  test/use_case/display_pets/DisplayPetsInteractorTest.java
Labels: new feature

#272 added catbreedapi to ui
  src/app/GetBreedUseCaseFactory.java
  src/app/PetDetailUseCaseFactory.java
  src/data_access/CatBreedDAO.java
  src/interface_adapter/get_breed/GetBreedPresenter.java
  src/interface_adapter/pet_bio/PetBioState.java
  src/interface_adapter/pet_bio/PetBioViewModel.java
  src/view/PetDetailView.java
Labels: new feature

#276 img
  src/view/PetDetailView.java
Labels: new feature

#277 bookmark works now
  src/app/LoggedInUseCaseFactory.java
  src/app/RemoveBookmarkUseCaseFactory.java
  src/interface_adapter/bookmark/RemoveBookmarkPresenter.java
  src/use_case/bookmarks/AddBookmarkInteractor.java
  src/use_case/bookmarks/BookmarkOutputData.java
  src/use_case/bookmarks/RemoveBookmarkInteractor.java
  src/view/BookmarkView.java
  src/view/PetListingPanel.java
  test/use_case/bookmarks/BookmarkOutputDataTest.java
  test/use_case/bookmarks/RemoveBookmarkInteractorTest.java
Labels: new feature

#278 i made remove bookmark button kill the pet listing
  src/app/DisplayBookmarkUseCaseFactory.java
  src/app/LoggedInUseCaseFactory.java
  src/app/RemoveBookmarkUseCaseFactory.java
  src/interface_adapter/bookmark/RemoveBookmarkPresenter.java
  src/use_case/bookmarks/AddBookmarkInteractor.java
  src/use_case/bookmarks/BookmarkOutputData.java
  src/use_case/bookmarks/RemoveBookmarkInteractor.java
  src/use_case/display_bookmark_pets/DisplayBookmarkInteractor.java
  src/view/BookmarkView.java
Labels: new feature

#281 pet bio details REAL
  src/view/PetDetailView.java
Labels: new feature

#282 fixed so that error actually shows instead of successs
  src/interface_adapter/bookmark/AddBookmarkPresenter.java
  src/interface_adapter/bookmark/RemoveBookmarkPresenter.java
Labels: bug fix

#284 fixed issue where program crashses when clicking back button in bookmarked pet view
  src/interface_adapter/bookmark/BookmarkState.java
  src/interface_adapter/display_bookmark_pets/DisplayBookmarkPresenter.java
Labels: bug fix

#287 some more tests
  test/data_access/CatBreedDAOTest.java
  test/use_case/adopt/AdoptTest.java
Labels: bug fix

#292 bookmark view and preference view
  src/app/DisplayPetsUseCaseFactory.java
  src/app/Main.java
  src/app/PetDetailUseCaseFactory.java
  src/app/PreferenceUsecaseFactory.java
  src/interface_adapter/PreferenceState.java
  src/interface_adapter/bookmark/BookmarkViewModel.java
  src/interface_adapter/preference/PreferenceViewModel.java
  src/use_case/display_pets/DisplayPetsInteractor.java
  src/view/BookmarkView.java
  src/view/LabelTextPanel.java
  src/view/NotifUI.java
  src/view/PreferenceView.java
Labels: new feature

#295 made drop box in preference view for breed part 3
  data.json
  src/app/GetMatchingStringUseCaseFactory.java
  src/app/Main.java
  src/app/PreferenceUsecaseFactory.java
  src/data_access/APIInfoInterface.java
  src/data_access/FileApiInfoDAO.java
  src/interface_adapter/PreferenceState.java
  src/interface_adapter/get_matching/GetMatchingController.java
  src/interface_adapter/get_matching/GetMatchingPresenter.java
  src/interface_adapter/preference/PreferenceViewModel.java
  src/use_case/get_matching_strings/GetMatchStringInteractor.java
  src/use_case/get_matching_strings/GetMatchingStringInputBoundary.java
  src/use_case/get_matching_strings/GetMatchingStringInputData.java
  src/use_case/get_matching_strings/GetMatchingStringOutputBoundary.java
  src/use_case/get_matching_strings/GetMatchingStringOutputData.java
  src/view/PreferenceView.java
Labels: new feature

#298 some fixes
  src/data_access/FilePetDAO.java
  src/interface_adapter/preference/PreferenceState.java
  src/interface_adapter/preference/PreferenceViewModel.java
  src/view/PreferenceView.java
Labels: bug fix

#301 preference view almost done except for validation maybe can do if theres time
  src/data_access/APIInfoInterface.java
  src/data_access/FileApiInfoDAO.java
  src/data_access/FilePetDAO.java
  src/data_access/PetDAOInterface.java
  src/interface_adapter/get_matching/GetMatchingPresenter.java
  src/interface_adapter/preference/PreferenceState.java
  src/interface_adapter/preference/PreferenceViewModel.java
  src/use_case/get_matching_strings/GetMatchStringInteractor.java
  src/view/ComponentPair.java
  src/view/PreferenceInputField.java
  src/view/PreferenceTextView.java
  src/view/PreferenceView.java
Labels: new feature

#302 committed missing file
  src/data_access/PetDAOInterface.java
Labels: bug fix

#303 Login, Signup Issue solved
  src/view/LoginView.java
  src/view/SignupView.java
Labels: bug fix

#304 fixed some bug
  src/view/PetDetailView.java
Labels: bug fix

#305 Whitespace bug fixed
  src/use_case/login/LoginInputData.java
  src/use_case/signup/SignupInputData.java
  src/view/LoginView.java
  src/view/PreferenceView.java
  src/view/SignupView.java
Labels: bug fix

#313 added validation to preference page for fields breed and location and cleaned up preference view
  src/app/PreferenceUsecaseFactory.java
  src/data_access/APIInfoInterface.java
  src/data_access/FileApiInfoDAO.java
  src/entity/preference/UserPreference.java
  src/interface_adapter/get_matching/GetMatchingPresenter.java
  src/interface_adapter/preference/PreferenceController.java
  src/interface_adapter/preference/PreferenceKeys.java
  src/interface_adapter/preference/PreferencePresenter.java
  src/interface_adapter/preference/PreferenceState.java
  src/interface_adapter/preference/PreferenceViewModel.java
  src/use_case/get_matching_strings/GetMatchStringInteractor.java
  src/use_case/get_matching_strings/GetMatchingStringOutputBoundary.java
  src/use_case/preference/PreferenceData.java
  src/use_case/preference/PreferenceInteractor.java
  src/use_case/preference/PreferenceOutputBoundary.java
  src/view/PreferenceView.java
  src/view/ProfileView.java
  test/use_case/preference/PreferenceInteractorTest.java
Labels: javadoc, new feature

#314 added validation to preference page for fields breed and location and cleaned up preference view
  src/view/PreferenceView.java
Labels: javadoc, new feature

#316 added data dao test
  src/data_access/APIInfoInterface.java
  src/data_access/FileApiInfoDAO.java
  src/data_access/RescueAPIAbstract.java
  test/data_access/FileApiInfoDAOIntegrationTest.java
Labels: help wanted

#325 made some bug fixes and added some tests
  src/data_access/FileApiInfoDAO.java
  src/data_access/FileUserDAO.java
  src/entity/Pet.java
  src/entity/user/AdopterUser.java
  src/use_case/adopt/Adopt.java
  src/use_case/get_matching_strings/GetMatchStringInteractor.java
  src/use_case/preference/PreferenceInteractor.java
  src/use_case/preference/PreferenceOutputData.java
  src/use_case/signup/SignupInteractor.java
  test/data_access/FileUserDAOTest.java
  test/use_case/adopt/AdoptTest.java
  test/use_case/get_matching_strings/GetMatchStringInteractorTest.java
  test/use_case/login/LoginInteractorTest.java
  test/use_case/preference/PreferenceInteractorTest.java
  test/use_case/signup/SignupInteractorTest.java
Labels: new feature, bug fix

#331 fix
  src/interface_adapter/display_pets/DisplayPetsViewModel.java
  test/data_access/FileUserDAOTest.java
Labels: bug fix

#332 read me update
  README.md
Labels: help wanted
